services:
  hello_odoo:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: hello_odoo
    restart: always         
    image: odoo:18.0
    network_mode: bridge
    ports:
      - "8069:8069"
      - "8071:8071" 
      - "8072:8072" # live chat
    command: --
    environment:
      - HOST=host.docker.internal
      - USER=hello
      - PASSWORD=h
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      # - odoo-web-data:/var/lib/odoo
      # - ./config:/etc/odoo
      - /app/odoo/addons:/mnt/extra-addons
# volumes:
#   odoo-web-data:    